# Generated by Django 2.1.2 on 2018-10-30 18:38

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_maps_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maps',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
