# Generated by Django 2.1.2 on 2018-10-30 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20181030_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
