# Generated by Django 2.1.2 on 2018-10-30 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_maps_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='maps',
            name='address',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
